name: Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

# Aynı branchtaki eşzamanlı koşular iptal olmasın
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      # Gradle Wrapper yoksa üret (AGP 8.5 ↔ Gradle 8.7 uyumlu)
      - name: Ensure Gradle Wrapper (8.7)
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Wrapper yok, üretiliyor..."
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.7
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x ./gradlew
          ./gradlew --version

      # Gradle cache (indirilen bağımlılıkları hızlandırır)
      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v4

      # Bellek ve paralellik sınırlı; daemon kapalı → CI daha stabil
      - name: Build Debug APK
        run: |
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "org.gradle.workers.max=2" >> gradle.properties
          ./gradlew assembleDebug --stacktrace --warning-mode all --info --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
