name: Android APK (Debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      # Gradle Wrapper yoksa üret → 8.7'ye sabitle
      - name: Ensure Gradle Wrapper (8.7)
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Wrapper yok, üretiliyor..."
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.7
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x ./gradlew
          ./gradlew --version

      # Yapı düzgün mü? (app klasörü gerçekten kökte mi?)
      - name: Show tree
        run: |
          ls -la
          ls -la app || true

      - name: Build Debug APK (daha fazla log)
        run: ./gradlew assembleDebug --stacktrace --warning-mode all --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
